### ISSUE TITLE
sigsafe_printf does not recognize the "j" length modifier

### ISSUE THREAD

**Issue by dabright** [rsyslog/liblogging#28]
The __stdlog_sigsafe_printf() function does not recognize the "j" length modifier indicating that the argument is of type intmax_t (e.g., "%jd") or uintmax_t (e.g., "%ju").

**Comment by dabright** [comment]
I'll have a pull request with fix soon.

**Comment by dabright** [comment]
Pull request submitted.

**Comment by rgerhards** [comment]
PR merged (sorry for being late)
