### ISSUE TITLE
build_file_line and build_syslog_frame call the __stdlog_print_* functions incorrectly

### ISSUE THREAD

**Issue by dabright** [rsyslog/liblogging#33]
In constructing the message header, both file.c/build_file_line() and uxsock.c/build_syslog_frame() will call the __stdlog_fmt_print_\* functions. However, in so doing, it incorrectly passes the buffer length _minus the length of the characters already inserted_. Those functions already take into account the length of the characters previously inserted into the buffer, so there is no reason to subtract their length. Doing so will cause needless truncation of the messages. Granted, this will only be a problem with very short buffer lengths, but you can see the effect when running the tester.c program (which uses such a short buffer). See the output from this sample run (using the syslog: channel spec):

`Jun  9 11:45:30 testhost001 : Test abc, 4712,`

You can see that the TAG ("tester", the ident supplied in stdlog_open()) is missing but the following colon and the first part of the message text is present. The TAG is missing since when calling the __stdlog_fmt_print_str() call, the size of the buffer passed is 40 (the actual buffer size) - 21 (the current value of idx) = 19, so when __stdlog_fmt_print_str() checks the room available it checks 21 against the passed-in buffer size (19) and finds the buffer (over-)full and so does not insert any characters. 

The corrected log line would look like:

`Jun  9 11:45:30 testhost001 tester: Test abc,`

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/liblogging/pull/35, part of 1.0.6
